In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
y= np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### np.arange 함수로 생성

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(np.arange(10))

numpy.ndarray

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [20]:
arr = np.array([1,2,3,4])
print('shape:',arr.shape)
print('dim:',arr.ndim)

shape: (4,)
dim: 1


In [19]:
arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print('shape:',arr2.shape)
print('dim:',arr2.ndim)

shape: (2, 4)
dim: 2


In [22]:
arr3 = np.arange(10)
print('shape:',arr3.shape)
print('dim:',arr3.ndim)

shape: (10,)
dim: 1


### np.zeros, np.ones

In [31]:
np.ones((4,5),dtype=np.uint8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [34]:
np.ones((2,3,4),dtype=np.uint8)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=uint8)

In [35]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### np.empty, np.full

In [36]:
np.empty((3,4))

array([[1.10624680e-311, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.12465777e-312, 1.31370903e-076, 4.75683495e-090,
        7.78961124e-071],
       [1.00512313e-047, 9.52402452e-047, 3.99910963e+252,
        1.90979636e-312]])

In [37]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### np.eye
 - 단위행렬

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.linspace
- np.linspace(시작, 끝, 몇개?)
- np.linspace(1,10,3)-> 1과10두수를 포함해서 총 3개의 값이 분포

In [39]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [43]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [44]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### reshape

In [28]:
arr4=np.arange(1,17) # 1~16
arr4 = arr4.reshape(4,4)
arr4.shape

(4, 4)

In [29]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## random 모듈

### rand 함수
- 0,1 사이의 값으로 랜덤한 ndarray생성

In [45]:
np.random.rand(4,5)

array([[0.09021418, 0.8788292 , 0.90223057, 0.32254657, 0.11893638],
       [0.52754473, 0.61021502, 0.86029321, 0.58615325, 0.05458029],
       [0.75433598, 0.35806546, 0.40053529, 0.69890252, 0.46972241],
       [0.91355298, 0.05872463, 0.29017077, 0.55642464, 0.58025361]])

### randn함수
- n: normal distribution(정규분포)
- 정규분포로 샘플링된 랜덤 ndarray생성

In [46]:
np.random.randn(5)

array([-0.55431606,  0.52340837,  0.45426306, -1.02064233,  1.17163804])

In [47]:
 np.random.randn(3,4,2)

array([[[ 0.0054465 ,  1.28048709],
        [-1.49278688, -2.37748948],
        [-0.48652128, -1.64895077],
        [ 0.21926635,  1.95044096]],

       [[ 0.74589296, -0.67136066],
        [-0.57095313, -0.05233396],
        [-0.40137612, -0.25717007],
        [-1.91240819,  1.51827106]],

       [[ 0.33169157, -2.15591765],
        [-0.17161177, -0.43120942],
        [-1.35118017, -2.50955763],
        [-0.39474913,  0.55188476]]])

### randint
- 특정 정수 사이에서 랜덤하게 샘플링

In [50]:
np.random.randint(1,100,size=(5,))

array([70, 38, 52, 81, 60])

### choice
- 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
- 정수가 주어졌을경우, np.arange(해당숫자)로 간주

In [58]:
# 정수가 주어졌을경우, np.arange(해당숫자)로 간주
np.random.choice(100, size=(3,4))

array([[43, 66, 64, 18],
       [66,  0, 63, 76],
       [93, 54, 54, 80]])

In [57]:
x = np.array([1, 2, 3, 1.7, 5.5, 4.9])
np.random.choice(x,size=(2,2),replace=False)

array([[3. , 1.7],
       [4.9, 1. ]])

In [59]:
np.random.uniform(1.0,3.0,size=(3,4))

array([[1.75663114, 1.24068994, 1.99310203, 1.22538549],
       [1.7797511 , 2.50154612, 2.57293492, 1.48772609],
       [1.75490063, 1.52741716, 1.65263061, 1.27005678]])

In [60]:
np.random.normal(1.0,3.0,size=(3,4))

array([[-7.68432867,  5.93726043, -2.11591074, -1.99786817],
       [-0.88460798,  2.96415953, -2.10158135,  3.98166949],
       [ 6.53168332, -2.47728547,  6.60564306,  2.73923126]])

### indexing slicing

In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[5:8] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [68]:
arr_slice = arr[5:8] # 얕은복사
arr_slice[1] = 100
arr

array([  0,   1,   2,   3,   4,  12, 100,  12,   8,   9])

In [72]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [73]:
data = np.random.randn(7,4)
data

array([[-0.34692897, -0.41616989,  0.21955826, -1.32298232],
       [ 0.0672737 ,  2.09246229,  0.16759925,  0.206742  ],
       [-1.65410033,  0.65424439,  0.29579208,  0.53713105],
       [-0.44176329, -0.44188546,  0.84701639,  1.22673265],
       [ 0.58118364,  0.44043508,  1.18427839, -0.13119211],
       [-1.5470266 ,  0.71479233, -0.68197982,  0.35058409],
       [-0.3212019 ,  0.52370413, -2.35889681,  0.09767474]])

In [74]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [75]:
data[names == 'Bob']

array([[-0.34692897, -0.41616989,  0.21955826, -1.32298232],
       [-0.44176329, -0.44188546,  0.84701639,  1.22673265]])

In [78]:
data[names=='Bob', 2:]

array([[ 0.21955826, -1.32298232],
       [ 0.84701639,  1.22673265]])

In [79]:
data[names=='Bob', 3]

array([-1.32298232,  1.22673265])

In [81]:
data[~(names == 'Bob')]

array([[ 0.0672737 ,  2.09246229,  0.16759925,  0.206742  ],
       [-1.65410033,  0.65424439,  0.29579208,  0.53713105],
       [ 0.58118364,  0.44043508,  1.18427839, -0.13119211],
       [-1.5470266 ,  0.71479233, -0.68197982,  0.35058409],
       [-0.3212019 ,  0.52370413, -2.35889681,  0.09767474]])

In [82]:
cond = ~(names == 'Bob')
data[cond]

array([[ 0.0672737 ,  2.09246229,  0.16759925,  0.206742  ],
       [-1.65410033,  0.65424439,  0.29579208,  0.53713105],
       [ 0.58118364,  0.44043508,  1.18427839, -0.13119211],
       [-1.5470266 ,  0.71479233, -0.68197982,  0.35058409],
       [-0.3212019 ,  0.52370413, -2.35889681,  0.09767474]])

In [85]:
mask = (names=='Bob') | (names=='Will')
data[mask]

array([[-0.34692897, -0.41616989,  0.21955826, -1.32298232],
       [-1.65410033,  0.65424439,  0.29579208,  0.53713105],
       [-0.44176329, -0.44188546,  0.84701639,  1.22673265],
       [ 0.58118364,  0.44043508,  1.18427839, -0.13119211]])

In [86]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.21955826, 0.        ],
       [0.0672737 , 2.09246229, 0.16759925, 0.206742  ],
       [0.        , 0.65424439, 0.29579208, 0.53713105],
       [0.        , 0.        , 0.84701639, 1.22673265],
       [0.58118364, 0.44043508, 1.18427839, 0.        ],
       [0.        , 0.71479233, 0.        , 0.35058409],
       [0.        , 0.52370413, 0.        , 0.09767474]])

In [87]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.0672737 , 2.09246229, 0.16759925, 0.206742  ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.71479233, 0.        , 0.35058409],
       [0.        , 0.52370413, 0.        , 0.09767474]])

### 팬시색인

In [90]:
arr = np.empty((8,4))
for i in range(arr.shape[0]):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [91]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [92]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [98]:
arr1 = np.arange(32).reshape((8,4))
arr1.shape

(8, 4)

In [99]:
arr2 = np.arange(32).reshape(8,4)
arr2.shape

(8, 4)

In [100]:
arr = np.arange(32).reshape(8,4)
arr = arr[[1,5,7,2]][:,[0,3,1,2]]
arr

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [101]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [102]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [103]:
arr = arr.T
arr

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [106]:
arr = np.random.randn(6,3)
arr

array([[ 0.8667764 , -1.67379964, -1.07148916],
       [-0.14227419,  1.5746327 , -0.02253342],
       [ 1.96000678,  1.38847832,  0.26163482],
       [ 1.20052756, -1.94271775, -0.42278941],
       [ 0.53971672, -0.62790254, -0.65911622],
       [-0.3343266 ,  0.15272338,  0.24517203]])

In [107]:
np.dot(arr.T, arr)

array([[ 6.45750467, -1.67564789, -1.35800348],
       [-1.67564789, 11.40068371,  3.39391534],
       [-1.35800348,  3.39391534,  1.89034396]])

#### ravel, np.ravel
  - 다차원배열을 1차원으로 변경
  - 'order' 파라미터
    - 'C' - row 우선 변경
    - 'F - column 우선 변경

In [108]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
arr.reshape(15,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
np.ravel(arr,order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [110]:
np.ravel(arr,order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### flatten
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점: copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [113]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [114]:
arr2 = arr.flatten(order='F')
arr2

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

In [115]:
arr2 = arr.flatten(order='C')
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [117]:
arr = np.arange(36)
print(f'shape: {arr.shape} dim: {arr.ndim}')
arr

shape: (36,) dim: 1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [118]:
arr = np.arange(36).reshape(6,6)
print(f'shape: {arr.shape} dim: {arr.ndim}')
arr

shape: (6, 6) dim: 2


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [119]:
arr = np.arange(36).reshape(3,3,-1)
print(f'shape: {arr.shape} dim: {arr.ndim}')
arr

shape: (3, 3, 4) dim: 3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

## Numpy 데이터 연산
- https://numpy.org/devdocs/reference/


In [120]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
y= np.random.rand(15).reshape(3,5)
y

array([[0.88279827, 0.06819903, 0.17236836, 0.07878121, 0.30933816],
       [0.98079384, 0.14602945, 0.96958043, 0.27663386, 0.67491755],
       [0.19883135, 0.0325061 , 0.43994746, 0.66177624, 0.19009299]])

### 연산함수
- add, substract, multiply, divide

In [122]:
np.add(x,y)

array([[ 0.88279827,  1.06819903,  2.17236836,  3.07878121,  4.30933816],
       [ 5.98079384,  6.14602945,  7.96958043,  8.27663386,  9.67491755],
       [10.19883135, 11.0325061 , 12.43994746, 13.66177624, 14.19009299]])

In [123]:
np.divide(x,y)

array([[  0.        ,  14.6629641 ,  11.60305738,  38.08014799,
         12.93083251],
       [  5.0979113 ,  41.08760347,   7.2196177 ,  28.91909198,
         13.33496218],
       [ 50.29387912, 338.39799501,  27.27598427,  19.64410206,
         73.64816685]])

In [124]:
x+y

array([[ 0.88279827,  1.06819903,  2.17236836,  3.07878121,  4.30933816],
       [ 5.98079384,  6.14602945,  7.96958043,  8.27663386,  9.67491755],
       [10.19883135, 11.0325061 , 12.43994746, 13.66177624, 14.19009299]])

In [125]:
x-y

array([[-0.88279827,  0.93180097,  1.82763164,  2.92121879,  3.69066184],
       [ 4.01920616,  5.85397055,  6.03041957,  7.72336614,  8.32508245],
       [ 9.80116865, 10.9674939 , 11.56005254, 12.33822376, 13.80990701]])

In [126]:
x/y

array([[  0.        ,  14.6629641 ,  11.60305738,  38.08014799,
         12.93083251],
       [  5.0979113 ,  41.08760347,   7.2196177 ,  28.91909198,
         13.33496218],
       [ 50.29387912, 338.39799501,  27.27598427,  19.64410206,
         73.64816685]])

In [127]:
x*y

array([[0.        , 0.06819903, 0.34473672, 0.23634362, 1.23735266],
       [4.9039692 , 0.87617668, 6.78706298, 2.21307087, 6.07425795],
       [1.98831352, 0.35756713, 5.27936952, 8.60309112, 2.66130181]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [128]:
y

array([[0.88279827, 0.06819903, 0.17236836, 0.07878121, 0.30933816],
       [0.98079384, 0.14602945, 0.96958043, 0.27663386, 0.67491755],
       [0.19883135, 0.0325061 , 0.43994746, 0.66177624, 0.19009299]])

In [129]:
#평균
np.mean(y)

0.40550628645206116

In [130]:
np.max(y)

0.980793839193163

In [132]:
np.argmax(y) # 최대값이 위치한 곳의 인덱스

5

In [133]:
y.shape

(3, 5)

In [134]:
np.var(y)  # 분산

0.1075130597909055

In [135]:
np.median(y) # 가운데 위치한 값

0.2766338585225835

In [138]:
np.std(y) # 표준편차

0.3278918416046753

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [139]:
y

array([[0.88279827, 0.06819903, 0.17236836, 0.07878121, 0.30933816],
       [0.98079384, 0.14602945, 0.96958043, 0.27663386, 0.67491755],
       [0.19883135, 0.0325061 , 0.43994746, 0.66177624, 0.19009299]])

In [140]:
np.sum(y)

6.0825942967809175

In [141]:
np.cumsum(y)

array([0.88279827, 0.9509973 , 1.12336566, 1.20214687, 1.51148504,
       2.49227887, 2.63830832, 3.60788875, 3.88452261, 4.55944015,
       4.75827151, 4.79077761, 5.23072507, 5.89250131, 6.0825943 ])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [143]:
arr = np.random.randn(10)
arr

array([ 0.89400689,  1.22288409, -1.92234449, -0.08300294,  0.20384562,
       -1.22377927,  1.03146033,  1.88907406,  0.82777416,  0.69686972])

In [144]:
arr > 0

array([ True,  True, False, False,  True, False,  True,  True,  True,
        True])

In [145]:
np.any(arr>0)

True

In [146]:
np.all(arr != 0)

True

In [147]:
np.all(arr > 0)

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [148]:
arr

array([ 0.89400689,  1.22288409, -1.92234449, -0.08300294,  0.20384562,
       -1.22377927,  1.03146033,  1.88907406,  0.82777416,  0.69686972])

In [149]:
np.where(arr > 0 , arr, 0)

array([0.89400689, 1.22288409, 0.        , 0.        , 0.20384562,
       0.        , 1.03146033, 1.88907406, 0.82777416, 0.69686972])

#### axis 이해하기
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용

* axis를 파라미터로 갖는 함수를 이용하기
 - 거의 대부분의 연산 함수들이 axis 파라미터를 사용
 - 이 경우, 해당 값이 주어졌을 때, 해당 axis를 **따라서** 연산이 적용
   - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨
 - 예) np.sum, np.mean, np.any 등등

In [159]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [160]:
np.sum(arr)

105

In [161]:
np.sum(arr, axis=0)

105

In [162]:
np.sum(arr, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [163]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
np.sum(arr, axis=0)

array([15, 18, 21, 24, 27])

In [165]:
np.sum(arr, axis=1)

array([10, 35, 60])

arr3d = np.arange(36).reshape(3,4,3)
arr3d

In [167]:
np.sum(arr3d, axis=0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [168]:
np.sum(arr3d, axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [169]:
np.sum(arr3d, axis=2)

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

In [170]:
np.sum(arr3d, axis=-3)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [171]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [172]:
np.sum(arr3d, axis=(0,2))

array([117, 144, 171, 198])

In [175]:
a1 = np.array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])
a1

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [176]:
np.sum(arr3d, axis=0)

array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [177]:
# array([117, 144, 171, 198])
np.sum(a1,axis=1)

array([117, 144, 171, 198])

### 브로드캐스팅

In [182]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,103)
c = np.arange(1000,1004)
d = b.reshape(1,3)
print(a.shape,b.shape, c.shape, d.shape)

(4, 3) (3,) (4,) (1, 3)


In [183]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [184]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [185]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

#### Boolean indexing
  - ndarry 인덱싱 시, bool 리스트를 전달하여 True인 경우만 필터링
* 브로드캐스팅을 활용하여 ndarray로 부터 bool list 얻기
 - 예) 짝수인 경우만 찾아보기

In [188]:
arr =np.random.randint(1,100,size=10)
arr

array([76, 27, 93, 90, 59, 26, 82, 99, 65, 33])

In [190]:
#짝수
mask = arr%2==0 
mask

array([ True, False, False,  True, False,  True,  True, False, False,
       False])

In [191]:
arr[mask]

array([76, 90, 26, 82])

In [192]:
arr[arr%2 == 0]

array([76, 90, 26, 82])

In [193]:
arr[arr>30]

array([76, 93, 90, 59, 82, 99, 65, 33])

####  다중조건 사용하기
 - 파이썬 논리 연산지인 and, or, not 키워드 사용 불가
 - & - AND 
 - | - OR 

In [195]:
mask = (arr%2==0) & (arr < 30)
arr[mask]

array([26])

In [196]:
arr[(arr<30) | (arr>50)]

array([76, 27, 93, 90, 59, 26, 82, 99, 65])

In [197]:
arr[(arr>30) & (arr<50)]

array([33])

In [105]:
# 6월의 온도
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

- 평균기온이 25도를 넘는 날의 수는?
- 평균기온이 25도를 넘은 날의 평균 기온은?

In [106]:
temp

array([23.9, 24.4, 24.1, 25.4, 27.6, 29.7, 26.7, 25.1, 25. , 22.7, 21.9,
       23.6, 24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 28.6, 28. , 25.1, 26.7,
       28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [107]:
mask = temp > 25.0
temp[mask]

array([25.4, 27.6, 29.7, 26.7, 25.1, 25.9, 25.6, 26.9, 28.6, 28. , 25.1,
       26.7, 28.1, 26.5, 26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [108]:
print(f'평균기온이 25도를 넘는 날의 수 : {len(temp[mask])}일')

평균기온이 25도를 넘는 날의 수 : 21일


In [109]:
avg = np.mean(temp[mask])
print(f'평균기온이 25도를 넘는 날의 수 : {len(temp[mask])}일(평균기온 : {avg:.1f}도)')

평균기온이 25도를 넘는 날의 수 : 21일(평균기온 : 26.9도)
